CARS = {
    1: {"name": "🚲 Велосипед", "level_required": 1, "price": 100, "is_premium": False},
    2: {"name": "🛵 Honda Dio", "level_required": 2, "price": 1000, "is_premium": False},
    3: {"name": "🚗 Lada 2107", "level_required": 3, "price": 3000, "is_premium": False},
    4: {"name": "🚙 Daewoo Matiz", "level_required": 4, "price": 7000, "is_premium": False},
    5: {"name": "🚗 Renault Logan", "level_required": 5, "price": 15000, "is_premium": False},
    6: {"name": "🚗 Hyundai Accent", "level_required": 6, "price": 25000, "is_premium": False},
    7: {"name": "🚙 Kia Rio", "level_required": 7, "price": 40000, "is_premium": False},
    8: {"name": "🚐 Volkswagen Golf IV", "level_required": 8, "price": 60000, "is_premium": False},
    9: {"name": "🚙 Chevrolet Niva", "level_required": 9, "price": 85000, "is_premium": False},
    10: {"name": "🚗 Ford Focus II", "level_required": 10, "price": 100000, "is_premium": False},
    11: {"name": "🚗 Toyota Camry", "level_required": 11, "price": 130000, "is_premium": False},
    12: {"name": "🚙 Nissan X-Trail", "level_required": 12, "price": 40000, "is_premium": False},
    13: {"name": "🚗 Tesla Model 3", "level_required": 13, "price": 50000, "is_premium": False},
    14: {"name": "🚗 BMW 3 Series", "level_required": 14, "price": 60000, "is_premium": False},
    15: {"name": "🚗 Mercedes-Benz C-Class", "level_required": 15, "price": 75000, "is_premium": False},
    16: {"name": "🚙 Toyota Land Cruiser Prado", "level_required": 16, "price": 90000, "is_premium": False},
    17: {"name": "🏎 Audi A5 Coupe", "level_required": 17, "price": 100000, "is_premium": False},
    18: {"name": "🚗 Lexus RX", "level_required": 18, "price": 120000, "is_premium": False},
    19: {"name": "🚙 Porsche Macan", "level_required": 19, "price": 150000, "is_premium": False},
    20: {"name": "🏎 Jaguar F-Type", "level_required": 20, "price": 180000, "is_premium": False},
    21: {"name": "🏎 BMW M5", "level_required": 21, "price": 220000, "is_premium": False},
    22: {"name": "🚙 Range Rover Sport", "level_required": 22, "price": 250000, "is_premium": False},
    23: {"name": "🏎 Porsche 911 Carrera", "level_required": 23, "price": 300000, "is_premium": False},
    24: {"name": "🏎 Lamborghini Huracán", "level_required": 24, "price": 500000, "is_premium": False},
    25: {"name": "🏎 Ferrari 488 GTB", "level_required": 25, "price": 700000, "is_premium": False},
    26: {"name": "🏎 Rolls-Royce Phantom", "level_required": 26, "price": 1000000, "is_premium": True},
    27: {"name": "🏎 Bugatti Chiron", "level_required": 27, "price": 1500000, "is_premium": True},
    28: {"name": "🚀 Tesla Cybertruck", "level_required": 28, "price": 2000000, "is_premium": True},
    29: {"name": "🛫 DeLorean DMC-12", "level_required": 29, "price": 2500000, "is_premium": True},
    30: {"name": "🚀 Pagani Huayra Roadster BC", "level_required": 30, "price": 3000000, "is_premium": True}
}


HOUSES = {
    1: {"name": "Заброшенная комната в общежитии", "level_required": 1, "price": 500, "is_premium": False},
    2: {"name": "Старая однокомнатная квартира на окраине", "level_required": 2, "price": 2000, "is_premium": False},
    3: {"name": "Ветхий домик в пригороде", "level_required": 3, "price": 4000, "is_premium": False},
    4: {"name": "Комната в коммунальной квартире", "level_required": 4, "price": 8000, "is_premium": False},
    5: {"name": "Маленькая студия в спальном районе", "level_required": 5, "price": 16000, "is_premium": False},
    6: {"name": "Двухкомнатная квартира без ремонта", "level_required": 6, "price": 30000, "is_premium": False},
    7: {"name": "Дом-барак в малоизвестном районе", "level_required": 7, "price": 50000, "is_premium": False},
    8: {"name": "Одноэтажный дом за городом", "level_required": 8, "price": 25000, "is_premium": False},
    9: {"name": "Квартира в центре с минимальными удобствами", "level_required": 9, "price": 35000, "is_premium": False},
    10: {"name": "Таунхаус в развивающемся районе", "level_required": 10, "price": 50000, "is_premium": False},
    11: {"name": "Современная квартира в деловом центре", "level_required": 11, "price": 75000, "is_premium": False},
    12: {"name": "Коттедж с небольшим участком", "level_required": 12, "price": 100000, "is_premium": False},
    13: {"name": "Дом на побережье", "level_required": 13, "price": 150000, "is_premium": False},
    14: {"name": "Апартаменты в престижном районе города", "level_required": 14, "price": 200000, "is_premium": False},
    15: {"name": "Пентхаус с видом на реку", "level_required": 15, "price": 300000, "is_premium": False},
    16: {"name": "Вилла с бассейном в пригороде", "level_required": 16, "price": 500000, "is_premium": False},
    17: {"name": "Двухэтажный особняк с гаражом", "level_required": 17, "price": 750000, "is_premium": False},
    18: {"name": "Современный лофт в центре мегаполиса", "level_required": 18, "price": 1000000, "is_premium": False},
    19: {"name": "Дом с частным садом и террасой", "level_required": 19, "price": 1500000, "is_premium": False},
    20: {"name": "Резиденция с панорамным остеклением", "level_required": 20, "price": 2500000, "is_premium": False},
    21: {"name": "Дом с личной пристанью для яхты", "level_required": 21, "price": 4000000, "is_premium": False},
    22: {"name": "Элитный пентхаус с вертолётной площадкой", "level_required": 22, "price": 6000000, "is_premium": False},
    23: {"name": "Вилла на частном острове", "level_required": 23, "price": 10000000, "is_premium": False},
    24: {"name": "Мегаособняк с теннисным кортом и спа-зоной", "level_required": 24, "price": 15000000, "is_premium": False},
    25: {"name": "Суперсовременный небоскрёб (верхние этажи в собственности)", "level_required": 25, "price": 25000000, "is_premium": False},
    26: {"name": "Особняк «Золотой век» с автоматизированной системой управления", "level_required": 26, "price": 40000000, "is_premium": True},
    27: {"name": "Замок в европейском стиле с охраняемой территорией", "level_required": 27, "price": 60000000, "is_premium": True},
    28: {"name": "Летающий дом на дирижабле с видом на мегаполис", "level_required": 28, "price": 100000000, "is_premium": True},
    29: {"name": "Подводная вилла с видом на океаническое дно", "level_required": 29, "price": 200000000, "is_premium": True},
    30: {"name": "Галактическая станция — жильё на орбите с возможностью торговли редкими ресурсами", "level_required": 30, "price": 500000000, "is_premium": True}
}



YACHTS = {
    1: {"name": "🛶 Старая гребная лодка (Rusty Row)", "level_required": 1, "price": 3000, "is_premium": False},
    2: {"name": "🛥 Подержанный моторный катер (WaveRunner 100)", "level_required": 2, "price": 6000, "is_premium": False},
    3: {"name": "🛶 Парусная лодка без каюты (Sea Breeze)", "level_required": 3, "price": 12000, "is_premium": False},
    4: {"name": "🚤 Недорогой скоростной катер (Storm Scout)", "level_required": 4, "price": 20000, "is_premium": False},
    5: {"name": "🛥 Рыбацкий катер (Ocean Fisher)", "level_required": 5, "price": 40000, "is_premium": False},
    6: {"name": "🛥 Маленький прогулочный катер (Coastal Cruiser)", "level_required": 6, "price": 70000, "is_premium": False},
    7: {"name": "🛶 Катамаран (Twin Tide)", "level_required": 7, "price": 75000, "is_premium": False},
    8: {"name": "🚤 Спортивный катер (Rapid Wave)", "level_required": 8, "price": 100000, "is_premium": False},
    9: {"name": "🛥 Мини-яхта с одной каютой (SunChaser)", "level_required": 9, "price": 150000, "is_premium": False},
    10: {"name": "🚤 Яхта-кабриолет (AquaVibe)", "level_required": 10, "price": 250000, "is_premium": False},
    11: {"name": "🛥 Двухпалубная яхта (Blue Horizon)", "level_required": 11, "price": 400000, "is_premium": False},
    12: {"name": "🛳 Круизная яхта (Ocean Dreamer)", "level_required": 12, "price": 600000, "is_premium": False},
    13: {"name": "🛳 Роскошная парусная яхта (Wind Whisperer)", "level_required": 13, "price": 800000, "is_premium": False},
    14: {"name": "🚤 Яхта с джакузи (Sea Mirage)", "level_required": 14, "price": 1000000, "is_premium": False},
    15: {"name": "🛥 Спортивная моторная яхта (TideRunner X)", "level_required": 15, "price": 1500000, "is_premium": False},
    16: {"name": "🛳 Премиум-яхта с бассейном (Golden Dolphin)", "level_required": 16, "price": 2000000, "is_premium": False},
    17: {"name": "🛳 Яхта с вертолётной площадкой (AeroMarine)", "level_required": 17, "price": 3000000, "is_premium": False},
    18: {"name": "🛥 Суперяхта с кинозалом (Ocean Luxe)", "level_required": 18, "price": 4500000, "is_premium": False},
    19: {"name": "🛳 Гибридная яхта (EcoSailor)", "level_required": 19, "price": 6000000, "is_premium": False},
    20: {"name": "🛳 Яхта-особняк (Crystal Wave)", "level_required": 20, "price": 8000000, "is_premium": False},
    21: {"name": "🛳 Экспедиционная яхта (Arctic Explorer)", "level_required": 21, "price": 10000000, "is_premium": False},
    22: {"name": "🛥 Плавучий ночной клуб (Neptune Nights)", "level_required": 22, "price": 12000000, "is_premium": False},
    23: {"name": "🛳 Суперяхта класса люкс (Elysium Pearl)", "level_required": 23, "price": 15000000, "is_premium": False},
    24: {"name": "🚀 Высокоскоростная суперяхта (ThunderFlash)", "level_required": 24, "price": 18000000, "is_premium": False},
    25: {"name": "🛳 Мега-яхта с двумя бассейнами (Titan Sovereign)", "level_required": 25, "price": 22000000, "is_premium": False},
    26: {"name": "🛳 Плавучий дворец (Royal Eternity)", "level_required": 26, "price": 27000000, "is_premium": True},
    27: {"name": "🛥 Неоновая яхта будущего (AquaNova)", "level_required": 27, "price": 32000000, "is_premium": True},
    28: {"name": "🛳 Яхта-казино (Fortune Star)", "level_required": 28, "price": 40000000, "is_premium": True},
    29: {"name": "🚀 Субмарина-яхта (DeepSea Phantom)", "level_required": 29, "price": 50000000, "is_premium": True},
    30: {"name": "🚀 Космояхта (Stellar Odyssey)", "level_required": 30, "price": 100000000, "is_premium": True}
}




PLANES = {
    1: {"name": "🪂 Параплан (WindRider)", "level_required": 1, "price": 5000, "is_premium": False},
    2: {"name": "🛩 Старый планер (SkyGlide)", "level_required": 2, "price": 10000, "is_premium": False},
    3: {"name": "🛩 Одноместный спортивный самолёт (AeroSwift 100)", "level_required": 3, "price": 20000, "is_premium": False},
    4: {"name": "🛩 Винтовой самолёт (Cessna 172)", "level_required": 4, "price": 40000, "is_premium": False},
    5: {"name": "🚁 Старый вертолёт (HeliScout)", "level_required": 5, "price": 80000, "is_premium": False},
    6: {"name": "🛩 Биплан (SkyDancer)", "level_required": 6, "price": 150000, "is_premium": False},
    7: {"name": "🚁 Бюджетный вертолёт (Bell 206 JetRanger)", "level_required": 7, "price": 250000, "is_premium": False},
    8: {"name": "🛩 Лёгкий частный самолёт (Piper PA-28 Cherokee)", "level_required": 8, "price": 400000, "is_premium": False},
    9: {"name": "🚁 Гражданский вертолёт (Robinson R44)", "level_required": 9, "price": 600000, "is_premium": False},
    10: {"name": "🛩 Турбовинтовой самолёт (Pilatus PC-12)", "level_required": 10, "price": 800000, "is_premium": False},
    11: {"name": "🛫 Бизнес-джет (Embraer Phenom 300)", "level_required": 11, "price": 1000000, "is_premium": False},
    12: {"name": "🛫 Региональный самолёт (Bombardier CRJ200)", "level_required": 12, "price": 1500000, "is_premium": False},
    13: {"name": "🚁 Продвинутый вертолёт (Airbus H145)", "level_required": 13, "price": 2000000, "is_premium": False},
    14: {"name": "🛫 Реактивный частный самолёт (Cessna Citation XLS)", "level_required": 14, "price": 3000000, "is_premium": False},
    15: {"name": "🛫 Среднемагистральный лайнер (Airbus A320)", "level_required": 15, "price": 5000000, "is_premium": False},
    16: {"name": "🛩 Спортивно-туристический самолёт (Diamond DA62)", "level_required": 16, "price": 7500000, "is_premium": False},
    17: {"name": "🛫 Грузопассажирский самолёт (Boeing 737-800)", "level_required": 17, "price": 10000000, "is_premium": False},
    18: {"name": "🛫 Люксовый бизнес-джет (Gulfstream G550)", "level_required": 18, "price": 15000000, "is_premium": False},
    19: {"name": "🛫 Сверхзвуковой бизнес-джет (Aerion AS2)", "level_required": 19, "price": 20000000, "is_premium": False},
    20: {"name": "🛫 Большой деловой самолёт (Bombardier Global 7500)", "level_required": 20, "price": 30000000, "is_premium": False},
    21: {"name": "🛫 Военный истребитель (F-16 Falcon)", "level_required": 21, "price": 40000000, "is_premium": False},
    22: {"name": "🛫 Пассажирский лайнер (Boeing 787 Dreamliner)", "level_required": 22, "price": 50000000, "is_premium": False},
    23: {"name": "🚀 Гиперзвуковой самолёт (Spike S-512)", "level_required": 23, "price": 75000000, "is_premium": False},
    24: {"name": "🛫 Роскошный лайнер (Boeing 747 VIP Edition)", "level_required": 24, "price": 100000000, "is_premium": False},
    25: {"name": "🛫 Президентский лайнер (AirForce One Replica)", "level_required": 25, "price": 150000000, "is_premium": False},
    26: {"name": "🚁 Вертолёт-яхта (SkyLux Heli)", "level_required": 26, "price": 200000000, "is_premium": True},
    27: {"name": "🛫 Летающий отель (Cloud Haven)", "level_required": 27, "price": 300000000, "is_premium": True},
    28: {"name": "🚀 Космический шаттл (StarGlide X)", "level_required": 28, "price": 500000000, "is_premium": True},
    29: {"name": "🚀 Сверхзвуковой люкс-джет (Concorde Legacy)", "level_required": 29, "price": 750000000, "is_premium": True},
    30: {"name": "🛸 Личный космический корабль (Nebula One)", "level_required": 30, "price": 1000000000, "is_premium": True}
}


ISLANDS = {
    1: {"name": "🏖 Заброшенный остров (Остров Выживания)", "level_required": 1, "price": 10000, "is_premium": False},
    2: {"name": "🌿 Остров с бамбуковой хижиной (Тихая Пристань)", "level_required": 2, "price": 20000, "is_premium": False},
    3: {"name": "🏚 Скалистый остров (Каменная Гавань)", "level_required": 3, "price": 40000, "is_premium": False},
    4: {"name": "🌊 Песчаный остров (Золотой Берег)", "level_required": 4, "price": 80000, "is_premium": False},
    5: {"name": "🌴 Тропический остров (Пальмовый Уют)", "level_required": 5, "price": 150000, "is_premium": False},
    6: {"name": "🐚 Остров с ракушечным пляжем (Рай для Начинающих)", "level_required": 6, "price": 250000, "is_premium": False},
    7: {"name": "🏝 Остров с деревянным бунгало (Уголок Путешественника)", "level_required": 7, "price": 400000, "is_premium": False},
    8: {"name": "🪨 Остров с каменным утёсом (Скалистый Край)", "level_required": 8, "price": 600000, "is_premium": False},
    9: {"name": "🏡 Остров с небольшим домом (Первая Резиденция)", "level_required": 9, "price": 800000, "is_premium": False},
    10: {"name": "🌾 Остров с кокосовой плантацией (Кокосовый Бриз)", "level_required": 10, "price": 1000000, "is_premium": False},
    11: {"name": "🌴 Идиллический остров (Райский Уголок)", "level_required": 11, "price": 1500000, "is_premium": False},
    12: {"name": "🏝 Остров с частным пирсом (Морская Жемчужина)", "level_required": 12, "price": 2000000, "is_premium": False},
    13: {"name": "🏞 Остров с водопадом (Остров Свежести)", "level_required": 13, "price": 3000000, "is_premium": False},
    14: {"name": "🏖 Остров с песчаными дюнами (Золотой Мираж)", "level_required": 14, "price": 5000000, "is_premium": False},
    15: {"name": "🏝 Остров с собственной вертолётной площадкой (Skyline Haven)", "level_required": 15, "price": 7500000, "is_premium": False},
    16: {"name": "🌋 Остров с потухшим вулканом (Огненное Сердце)", "level_required": 16, "price": 10000000, "is_premium": False},
    17: {"name": "🏔 Горный остров (Высокий Берег)", "level_required": 17, "price": 15000000, "is_premium": False},
    18: {"name": "🌴 Остров с роскошной виллой (Вилла Солнца)", "level_required": 18, "price": 20000000, "is_premium": False},
    19: {"name": "🏜 Остров в стиле сафари (Остров Приключений)", "level_required": 19, "price": 30000000, "is_premium": False},
    20: {"name": "🏰 Остров с мини-замком (Легендарная Обитель)", "level_required": 20, "price": 40000000, "is_premium": False},
    21: {"name": "🛩 Остров с личным аэродромом (SkyPort Island)", "level_required": 21, "price": 50000000, "is_premium": False},
    22: {"name": "🌿 Остров с плантациями редких растений (Зелёное Золото)", "level_required": 22, "price": 75000000, "is_premium": False},
    23: {"name": "🏞 Остров с мраморным дворцом (Белая Гавань)", "level_required": 23, "price": 100000000, "is_premium": False},
    24: {"name": "🏖 Остров с яхтенной мариной (Harbor Luxe)", "level_required": 24, "price": 150000000, "is_premium": False},
    25: {"name": "🏢 Остров-город (Мегаполис Мечты)", "level_required": 25, "price": 200000000, "is_premium": False},
    26: {"name": "🪐 Остров на плавучей платформе (FutureWave)", "level_required": 26, "price": 300000000, "is_premium": True},
    27: {"name": "🏯 Остров с японским дворцом (Сакура Айленд)", "level_required": 27, "price": 400000000, "is_premium": True},
    28: {"name": "🌌 Остров-курорт с лазерным шоу (Ночной Бриллиант)", "level_required": 28, "price": 500000000, "is_premium": True},
    29: {"name": "🏝 Остров-казино (Fortune Isle)", "level_required": 29, "price": 750000000, "is_premium": True},
    30: {"name": "🌟 Летающий остров (SkyLegend)", "level_required": 30, "price": 1000000000, "is_premium": True}
}

