MINING_FARMS = {
    # ⛏ Начальные майнинг-фермы (1–10) — дешёвое оборудование, низкая производительность
    1: {
        "name": "🖥 Старый ноутбук (Dusty Miner)",
        "base_cost": 50000,
        "base_income": 10,
        "experience_bonus": 5,
        "max_working_hours": 4,
        "is_premium": False,
        "level_required": 1,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    2: {
        "name": "💻 Один б/у ПК (Single Rig 1000)",
        "base_cost": 100000,
        "base_income": 25,
        "experience_bonus": 10,
        "max_working_hours": 6,
        "is_premium": False,
        "level_required": 2,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    3: {
        "name": "🖨 ПК с одной видеокартой (Budget Miner)",
        "base_cost": 200000,
        "base_income": 50,
        "experience_bonus": 15,
        "max_working_hours": 8,
        "is_premium": False,
        "level_required": 3,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    4: {
        "name": "🧱 Подержанный майнинг-риг (Old Rig S1)",
        "base_cost": 400000,
        "base_income": 80,
        "experience_bonus": 20,
        "max_working_hours": 8,
        "is_premium": False,
        "level_required": 4,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    5: {
        "name": "🖧 Мини-ферма в кладовке (Closet Crypto)",
        "base_cost": 600000,
        "base_income": 120,
        "experience_bonus": 25,
        "max_working_hours": 10,
        "is_premium": False,
        "level_required": 5,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    6: {
        "name": "🌡 Ферма из офисных ПК (Office Miner)",
        "base_cost": 800000,
        "base_income": 150,
        "experience_bonus": 30,
        "max_working_hours": 10,
        "is_premium": False,
        "level_required": 6,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    7: {
        "name": "⚡ Домашняя ферма на 3 GPU (Home Hash 3000)",
        "base_cost": 1000000,
        "base_income": 200,
        "experience_bonus": 35,
        "max_working_hours": 12,
        "is_premium": False,
        "level_required": 7,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    8: {
        "name": "💡 Майнинг-риг с водяным охлаждением (CoolMiner X)",
        "base_cost": 1500000,
        "base_income": 300,
        "experience_bonus": 40,
        "max_working_hours": 12,
        "is_premium": False,
        "level_required": 8,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    9: {
        "name": "🔌 Ферма в гараже (Garage HashFarm)",
        "base_cost": 2000000,
        "base_income": 400,
        "experience_bonus": 45,
        "max_working_hours": 12,
        "is_premium": False,
        "level_required": 9,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },
    10: {
        "name": "⚙ Ферма на дешёвом оборудовании (Entry Pro Miner)",
        "base_cost": 2500000,
        "base_income": 500,
        "experience_bonus": 50,
        "max_working_hours": 12,
        "is_premium": False,
        "level_required": 10,
        "city_required": 1,
        "house_required": 1,
        "airplane_required": 0
    },

    # ⚡ Продвинутые майнинг-фермы (11–25) — высокая производительность, доступ к редким валютам
    11: {
        "name": "🏠 Ферма на арендованном складе (Warehouse Miner)",
        "base_cost": 5000000,
        "base_income": 1000,
        "experience_bonus": 60,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 11,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 0
    },
    12: {
        "name": "🔒 Ферма с защитой от сбоев (SecureHash Pro)",
        "base_cost": 7500000,
        "base_income": 1500,
        "experience_bonus": 70,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 12,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 0
    },
    13: {
        "name": "🌬 Ферма с промышленным охлаждением (CoolWave Miner)",
        "base_cost": 10000000,
        "base_income": 2000,
        "experience_bonus": 80,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 13,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 0
    },
    14: {
        "name": "🔥 ASIC-ферма начального уровня (ASIC Starter S3)",
        "base_cost": 15000000,
        "base_income": 3000,
        "experience_bonus": 90,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 14,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 0
    },
    15: {
        "name": "🚀 Мобильная ферма на грузовике (HashTruck)",
        "base_cost": 20000000,
        "base_income": 4000,
        "experience_bonus": 100,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 15,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    16: {
        "name": "🧪 Экспериментальная ферма на солнечной энергии (SolarHash Beta)",
        "base_cost": 25000000,
        "base_income": 5000,
        "experience_bonus": 110,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 16,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    17: {
        "name": "💎 Ферма для добычи редких токенов (RareCoin Hunter)",
        "base_cost": 30000000,
        "base_income": 6000,
        "experience_bonus": 120,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 17,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    18: {
        "name": "🏭 Индустриальная майнинг-ферма (MegaHash Factory)",
        "base_cost": 40000000,
        "base_income": 8000,
        "experience_bonus": 130,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 18,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    19: {
        "name": "🧊 Ферма с крио-охлаждением (CryoMiner Z)",
        "base_cost": 50000000,
        "base_income": 10000,
        "experience_bonus": 140,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 19,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    20: {
        "name": "🌐 Ферма с ИИ-управлением (AIMiner 5000)",
        "base_cost": 60000000,
        "base_income": 12000,
        "experience_bonus": 150,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 20,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    21: {
        "name": "⚡ Майнинг-ферма в дата-центре (DataMine Core)",
        "base_cost": 70000000,
        "base_income": 14000,
        "experience_bonus": 160,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 21,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    22: {
        "name": "🚉 Подземная ферма (SubHash Facility)",
        "base_cost": 80000000,
        "base_income": 16000,
        "experience_bonus": 170,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 22,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    23: {
        "name": "🌊 Ферма, охлаждаемая морской водой (OceanCool Miner)",
        "base_cost": 90000000,
        "base_income": 18000,
        "experience_bonus": 180,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 23,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    24: {
        "name": "⚛ Кластер майнинга с квантовым ускорителем (Quantum Hash X)",
        "base_cost": 100000000,
        "base_income": 20000,
        "experience_bonus": 190,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 24,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },
    25: {
        "name": "🏢 Майнинг-небоскрёб (SkyHash Tower)",
        "base_cost": 120000000,
        "base_income": 25000,
        "experience_bonus": 200,
        "max_working_hours": 16,
        "is_premium": False,
        "level_required": 25,
        "city_required": 2,
        "house_required": 2,
        "airplane_required": 1
    },

    # 💎 Привилегии за донат (26–30) — уникальные фермы с особыми бонусами
    26: {
        "name": "🚀 Орбитальная майнинг-станция (OrbitMine One)",
        "base_cost": 1,
        "base_income": 1,
        "experience_bonus": 1,
        "max_working_hours": 24,
        "is_premium": True,
        "level_required": 30,
        "city_required": 3,
        "house_required": 3,
        "airplane_required": 2
    },
    27: {
        "name": "🌙 Лунная ферма (MoonHash Station)",
        "base_cost": 1,
        "base_income": 1,
        "experience_bonus": 1,
        "max_working_hours": 24,
        "is_premium": True,
        "level_required": 30,
        "city_required": 3,
        "house_required": 3,
        "airplane_required": 2
    },
    28: {
        "name": "🧬 Квантово-блокчейновый центр (QuantumBlock HQ)",
        "base_cost": 1,
        "base_income": 1,
        "experience_bonus": 1,
        "max_working_hours": 24,
        "is_premium": True,
        "level_required": 30,
        "city_required": 3,
        "house_required": 3,
        "airplane_required": 2
    },
    29: {
        "name": "🌌 Майнинг-ферма на астероиде (Asteroid Miner X)",
        "base_cost": 1,
        "base_income": 1,
        "experience_bonus": 1,
        "max_working_hours": 24,
        "is_premium": True,
        "level_required": 30,
        "city_required": 3,
        "house_required": 3,
        "airplane_required": 2
    },
    30: {
        "name": "🪐 Галактический майнинг-комплекс (GalaxyHash Prime)",
        "base_cost": 1,
        "base_income": 1,
        "experience_bonus": 1,
        "max_working_hours": 24,
        "is_premium": True,
        "level_required": 30,
        "city_required": 3,
        "house_required": 3,
        "airplane_required": 2
    }
}